# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import taskqueue_pb2 as taskqueue__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in taskqueue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DistributorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/taskqueue.Distributor/Enqueue',
                request_serializer=taskqueue__pb2.Task.SerializeToString,
                response_deserializer=taskqueue__pb2.EnqueueReply.FromString,
                _registered_method=True)
        self.RequestTask = channel.unary_unary(
                '/taskqueue.Distributor/RequestTask',
                request_serializer=taskqueue__pb2.AgentInfo.SerializeToString,
                response_deserializer=taskqueue__pb2.Task.FromString,
                _registered_method=True)
        self.ReportDone = channel.unary_unary(
                '/taskqueue.Distributor/ReportDone',
                request_serializer=taskqueue__pb2.TaskDone.SerializeToString,
                response_deserializer=taskqueue__pb2.Empty.FromString,
                _registered_method=True)


class DistributorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Enqueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportDone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistributorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=taskqueue__pb2.Task.FromString,
                    response_serializer=taskqueue__pb2.EnqueueReply.SerializeToString,
            ),
            'RequestTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTask,
                    request_deserializer=taskqueue__pb2.AgentInfo.FromString,
                    response_serializer=taskqueue__pb2.Task.SerializeToString,
            ),
            'ReportDone': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportDone,
                    request_deserializer=taskqueue__pb2.TaskDone.FromString,
                    response_serializer=taskqueue__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskqueue.Distributor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskqueue.Distributor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Distributor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskqueue.Distributor/Enqueue',
            taskqueue__pb2.Task.SerializeToString,
            taskqueue__pb2.EnqueueReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskqueue.Distributor/RequestTask',
            taskqueue__pb2.AgentInfo.SerializeToString,
            taskqueue__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportDone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskqueue.Distributor/ReportDone',
            taskqueue__pb2.TaskDone.SerializeToString,
            taskqueue__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
