# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: taskqueue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'taskqueue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftaskqueue.proto\x12\ttaskqueue\"\x92\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\"\n\x04tier\x18\x03 \x01(\x0e\x32\x14.taskqueue.Task.Tier\x12\x13\n\x0b\x65xpected_ms\x18\x04 \x01(\x05\x12\x18\n\x10\x65nqueued_at_unix\x18\x05 \x01(\x03\"\x1a\n\x04Tier\x12\x08\n\x04\x46REE\x10\x00\x12\x08\n\x04PAID\x10\x01\"\'\n\x0c\x45nqueueReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x1d\n\tAgentInfo\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"<\n\x08TaskDone\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\r\n\x05notes\x18\x03 \x01(\t2\xad\x01\n\x0b\x44istributor\x12\x33\n\x07\x45nqueue\x12\x0f.taskqueue.Task\x1a\x17.taskqueue.EnqueueReply\x12\x34\n\x0bRequestTask\x12\x14.taskqueue.AgentInfo\x1a\x0f.taskqueue.Task\x12\x33\n\nReportDone\x12\x13.taskqueue.TaskDone\x1a\x10.taskqueue.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'taskqueue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=31
  _globals['_TASK']._serialized_end=177
  _globals['_TASK_TIER']._serialized_start=151
  _globals['_TASK_TIER']._serialized_end=177
  _globals['_ENQUEUEREPLY']._serialized_start=179
  _globals['_ENQUEUEREPLY']._serialized_end=218
  _globals['_EMPTY']._serialized_start=220
  _globals['_EMPTY']._serialized_end=227
  _globals['_AGENTINFO']._serialized_start=229
  _globals['_AGENTINFO']._serialized_end=258
  _globals['_TASKDONE']._serialized_start=260
  _globals['_TASKDONE']._serialized_end=320
  _globals['_DISTRIBUTOR']._serialized_start=323
  _globals['_DISTRIBUTOR']._serialized_end=496
# @@protoc_insertion_point(module_scope)
